# Generated by Django 5.0.1 on 2024-01-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
                ('priority', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('desc', models.TextField()),
            ],
        ),
    ]
